//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Discom.UP.Backend.UpDash.Base.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanguageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Discom.UP.Application.Base.Language.LanguageResource", typeof(LanguageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIML.
        /// </summary>
        internal static string AIML {
            get {
                return ResourceManager.GetString("AIML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archives.
        /// </summary>
        internal static string Archives {
            get {
                return ResourceManager.GetString("Archives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backend.
        /// </summary>
        internal static string Backend {
            get {
                return ResourceManager.GetString("Backend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal server error happened..
        /// </summary>
        internal static string Backend_InternalServerError {
            get {
                return ResourceManager.GetString("Backend_InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database type is unknown to the backend software..
        /// </summary>
        internal static string Backend_UnknownDatabaseType {
            get {
                return ResourceManager.GetString("Backend_UnknownDatabaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        internal static string Connection {
            get {
                return ResourceManager.GetString("Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to establish connection..
        /// </summary>
        internal static string Connection_Failed {
            get {
                return ResourceManager.GetString("Connection_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized to establish connection to service..
        /// </summary>
        internal static string Connection_Unauthorized {
            get {
                return ResourceManager.GetString("Connection_Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data gathering failed..
        /// </summary>
        internal static string Data_DataGatheringFailure {
            get {
                return ResourceManager.GetString("Data_DataGatheringFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data available..
        /// </summary>
        internal static string Data_NoDataAvailable {
            get {
                return ResourceManager.GetString("Data_NoDataAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        internal static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to databse failed..
        /// </summary>
        internal static string DataBase_ConnectionError {
            get {
                return ResourceManager.GetString("DataBase_ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database upgrade needed but denied..
        /// </summary>
        internal static string Database_UpgradeDenied {
            get {
                return ResourceManager.GetString("Database_UpgradeDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database upgrade failed..
        /// </summary>
        internal static string Database_UpgradeFailure {
            get {
                return ResourceManager.GetString("Database_UpgradeFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found..
        /// </summary>
        internal static string File_FileNotFound {
            get {
                return ResourceManager.GetString("File_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frontend.
        /// </summary>
        internal static string Frontend {
            get {
                return ResourceManager.GetString("Frontend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MeasurementData.
        /// </summary>
        internal static string MeasurementData {
            get {
                return ResourceManager.GetString("MeasurementData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The gathering of the measurement data failed..
        /// </summary>
        internal static string MeasurementData_DataGatheringFailure {
            get {
                return ResourceManager.GetString("MeasurementData_DataGatheringFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        internal static string Parameter {
            get {
                return ResourceManager.GetString("Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission.
        /// </summary>
        internal static string Permission {
            get {
                return ResourceManager.GetString("Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request is denied..
        /// </summary>
        internal static string Permission_Denied {
            get {
                return ResourceManager.GetString("Permission_Denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request is not defined..
        /// </summary>
        internal static string Permission_RequestUndefined {
            get {
                return ResourceManager.GetString("Permission_RequestUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not defined..
        /// </summary>
        internal static string Permission_UserUndefined {
            get {
                return ResourceManager.GetString("Permission_UserUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistence.
        /// </summary>
        internal static string Persistence {
            get {
                return ResourceManager.GetString("Persistence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductionData.
        /// </summary>
        internal static string ProductionData {
            get {
                return ResourceManager.GetString("ProductionData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topology.
        /// </summary>
        internal static string Topology {
            get {
                return ResourceManager.GetString("Topology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service capabilities do not match the topology..
        /// </summary>
        internal static string Topology_Mismatch {
            get {
                return ResourceManager.GetString("Topology_Mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        internal static string Validation {
            get {
                return ResourceManager.GetString("Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory is Mandatory..
        /// </summary>
        internal static string Validation_FactoryMandatory {
            get {
                return ResourceManager.GetString("Validation_FactoryMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line is mandatory..
        /// </summary>
        internal static string Validation_LineMandatory {
            get {
                return ResourceManager.GetString("Validation_LineMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines are mandatory..
        /// </summary>
        internal static string Validation_LinesMandatory {
            get {
                return ResourceManager.GetString("Validation_LinesMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one of the time-based filters (Time or LastN) is required..
        /// </summary>
        internal static string Validation_TimeOrTopNMandatory {
            get {
                return ResourceManager.GetString("Validation_TimeOrTopNMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waves.
        /// </summary>
        internal static string Waves {
            get {
                return ResourceManager.GetString("Waves", resourceCulture);
            }
        }
    }
}
